CGO_ENABLED=0 GOOS=windows  GOARCH=amd64 go build -ldflags="-s -w"  -o ./dist/fast-win-x64.exe .
CGO_ENABLED=0 GOOS=linux    GOARCH=amd64 go build -ldflags="-s -w"  -o ./dist/fast-linux-x64 .
CGO_ENABLED=0 GOOS=darwin   GOARCH=amd64 go build -ldflags="-s -w"  -o ./dist/fast-mac-x64 .
CGO_ENABLED=0 GOOS=linux    GOARCH=arm   go build -ldflags="-s -w"  -o ./dist/fast-linux-arm .
CGO_ENABLED=0 GOOS=darwin   GOARCH=arm   go build -ldflags="-s -w"  -o ./dist/fast-mac-arm .
CGO_ENABLED=0 GOOS=linux    GOARCH=arm64 go build -ldflags="-s -w"  -o ./dist/fast-linux-arm64 .
CGO_ENABLED=0 GOOS=darwin   GOARCH=arm64 go build -ldflags="-s -w"  -o ./dist/fast-mac-arm64 .
CGO_ENABLED=0 GOOS=linux    GOARCH=mips  go build -ldflags="-s -w"  -o ./dist/fast-linux-mips .
CGO_ENABLED=0 GOOS=darwin   GOARCH=mips  go build -ldflags="-s -w"  -o ./dist/fast-mac-mips .
CGO_ENABLED=0 GOOS=linux    GOARCH=mipsle go build -ldflags="-s -w"  -o ./dist/fast-linux-mipsle .
CGO_ENABLED=0 GOOS=darwin   GOARCH=mipsle go build -ldflags="-s -w"  -o ./dist/fast-mac-mipsle .
CGO_ENABLED=0 GOOS=linux    GOARCH=mips64 go build -ldflags="-s -w"  -o ./dist/fast-linux-mips64 .
CGO_ENABLED=0 GOOS=darwin   GOARCH=mips64 go build -ldflags="-s -w"  -o ./dist/fast-mac-mips64 .
CGO_ENABLED=0 GOOS=linux    GOARCH=mips64le go build -ldflags="-s -w"  -o ./dist/fast-linux-mips64le .
CGO_ENABLED=0 GOOS=darwin   GOARCH=mips64le go build -ldflags="-s -w"  -o ./dist/fast-mac-mips64le .
CGO_ENABLED=0 GOOS=linux    GOARCH=ppc64  go build -ldflags="-s -w"  -o ./dist/fast-linux-ppc64 .
CGO_ENABLED=0 GOOS=darwin   GOARCH=ppc64  go build -ldflags="-s -w"  -o ./dist/fast-mac-ppc64 .
CGO_ENABLED=0 GOOS=linux    GOARCH=ppc64le go build -ldflags="-s -w"  -o ./dist/fast-linux-ppc64le .
CGO_ENABLED=0 GOOS=darwin   GOARCH=ppc64le go build -ldflags="-s -w"  -o ./dist/fast-mac-ppc64le .
CGO_ENABLED=0 GOOS=linux    GOARCH=s390x  go build -ldflags="-s -w"  -o ./dist/fast-linux-s390x .
CGO_ENABLED=0 GOOS=darwin   GOARCH=s390x  go build -ldflags="-s -w"  -o ./dist/fast-mac-s390x .
CGO_ENABLED=0 GOOS=linux    GOARCH=wasm   go build -ldflags="-s -w"  -o ./dist/fast-linux-wasm .
CGO_ENABLED=0 GOOS=darwin   GOARCH=wasm   go build -ldflags="-s -w"  -o ./dist/fast-mac-wasm .
